# Generated by Django 3.0.8 on 2020-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_auto_20200903_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='', upload_to='Food/images'),
        ),
    ]
