# Generated by Django 3.0.8 on 2020-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_auto_20200911_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
