# Generated by Django 3.0.8 on 2020-09-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Chicken Momo', 'Chicken Momo'), ('Veg Pasta', 'Veg Pasta'), ('Masala Dosa', 'Masala Dosa'), ('Ras Malai', 'Ras Malai'), ('Uttapam', 'Uttapam'), ('Shorshe Ilish', 'Shorshe Ilish'), ('Chicken Thali', 'Chicken Thali'), ('Chicken Kebab', 'Chicken Kebab'), ('Lassi', 'Lassi'), ('Dal Bati Churma', 'Dal Bati Churma'), ('Hyderababdi Biryani', 'Hyderababdi Biryani'), ('Paneer Butter Masala', 'Paneer Butter Masala')], default='Lassi', max_length=200)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=200)),
                ('payment_method', models.CharField(choices=[('1', 'COD'), ('2', 'Debit/Credit/Net Banking')], default='COD', max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
