# Generated by Django 3.0.8 on 2020-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0007_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=50)),
                ('payment_method', models.CharField(default='', max_length=70)),
                ('price', models.CharField(default='', max_length=500)),
                ('name', models.CharField(default='', max_length=500)),
                ('mobile', models.CharField(default='', max_length=500)),
                ('address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
